### ISSUE TITLE
ChatControl is not working after update to 7.4.0

### ISSUE THREAD

**Issue by AndGK** [kangarko/ChatControl#221]
So, plugin is not working for almost 90% of it's features after the update, here's an example

```
[10:10:25] [pool-9-thread-1/INFO]: [0;30;1m[[0;36;1m[21mAuria[0;30;1m] [0;37;1m[0;36;1mandgk[0;32;1m had their existing parent groups cleared, and now only inherits [0;36;1mowner[0;32;1m in context [0;33;1mglobal[0;32;1m.[m
[10:10:25] [pool-9-thread-1/INFO]: [0;30;1m[[0;36;1m[21mAuria[0;30;1m] [0;37;1m[0;37;22m(User data was saved to storage)[m
[10:10:32] [Server thread/INFO]: <sqwat> ur op[m
[10:10:37] [Async Chat Thread - #8/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v7.4.0
java.lang.NoSuchMethodError: me.kangarko.chatcontrol.api.PreRuleMatchEvent.callEvent()Z
	at me.kangarko.chatcontrol.  .....lPT7.const(SourceFile:318) ~[?:?]
	at me.kangarko.chatcontrol.  .....lPT7.const(SourceFile:274) ~[?:?]
	at me.kangarko.chatcontrol.  .....coM8.const(SourceFile:174) ~[?:?]
	at me.kangarko.chatcontrol.  .....coM8.execute(SourceFile:43) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PlayerConnection.chat(PlayerConnection.java:1276) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1214) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by kangarko** [comment]
Confirmed. Will be fixed shortly.
